/****** Object:  Database [Genai]    Script Date: 06/19/2025 12:49:29 PM ******/
CREATE DATABASE [Genai]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Genai', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Genai.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Genai_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Genai_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Genai] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Genai].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Genai] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Genai] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Genai] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Genai] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Genai] SET ARITHABORT OFF 
GO
ALTER DATABASE [Genai] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Genai] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Genai] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Genai] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Genai] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Genai] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Genai] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Genai] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Genai] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Genai] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Genai] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Genai] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Genai] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Genai] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Genai] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Genai] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Genai] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Genai] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Genai] SET  MULTI_USER 
GO
ALTER DATABASE [Genai] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Genai] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Genai] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Genai] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Genai] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Genai] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Genai] SET QUERY_STORE = ON
GO
ALTER DATABASE [Genai] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
/****** Object:  Table [dbo].[chat_history]    Script Date: 06/19/2025 12:49:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[chat_history](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[emp_id] [varchar](50) NOT NULL,
	[messages] [nvarchar](max) NOT NULL,
	[expires_at] [datetime] NOT NULL,
	[created_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[employees]    Script Date: 06/19/2025 12:49:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[employees](
	[id] [varchar](20) NOT NULL,
	[surname] [varchar](100) NOT NULL,
	[vacation_days] [int] NULL,
	[position] [varchar](50) NULL,
	[department] [varchar](50) NULL,
	[hire_date] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [idx_chat_history_emp_id]    Script Date: 06/19/2025 12:49:30 PM ******/
CREATE NONCLUSTERED INDEX [idx_chat_history_emp_id] ON [dbo].[chat_history]
(
	[emp_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [idx_chat_history_expires]    Script Date: 06/19/2025 12:49:30 PM ******/
CREATE NONCLUSTERED INDEX [idx_chat_history_expires] ON [dbo].[chat_history]
(
	[expires_at] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[chat_history] ADD  DEFAULT (getdate()) FOR [created_at]
GO
ALTER TABLE [dbo].[employees] ADD  DEFAULT ((20)) FOR [vacation_days]
GO
ALTER TABLE [dbo].[chat_history]  WITH CHECK ADD  CONSTRAINT [CK_messages_is_json] CHECK  ((isjson([messages])=(1)))
GO
ALTER TABLE [dbo].[chat_history] CHECK CONSTRAINT [CK_messages_is_json]
GO
/****** Object:  StoredProcedure [dbo].[sp_cleanup_expired_chats]    Script Date: 06/19/2025 12:49:30 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_cleanup_expired_chats]
AS
BEGIN
    DELETE FROM chat_history WHERE expires_at < GETDATE();
END;
GO
ALTER DATABASE [Genai] SET  READ_WRITE 
GO
